### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by carcaschoi** [dezem/AtmoXL-Titel-Installer#1]
Add a updater inside ATMOXL-TITEL-INSTALLER. So that it can update latest releases automatically

**Comment by dezem** [comment]
Will be in the next release, but i have no ETA yet

**Comment by carcaschoi** [comment]
You may use 「tinwoo」 as reference. It built in a updater

**Comment by dezem** [comment]
Re added on release -> https://github.com/dezem/AtmoXL-Titel-Installer/releases/tag/1.5.0
