### ISSUE TITLE
Theme Customization in app

### ISSUE THREAD

**Issue by DraconicNEO** [dezem/AtmoXL-Titel-Installer#16]
Hello I think it would be a good idea to be able to customize the appearance of the Installer so users could change the background picture and the color scheme.

**Comment by impeeza** [comment]
Add theme support like homebrew launcher does

**Comment by dezem** [comment]
To replace the background with your custom one.
You can place your "background.png" (1280x720) to the NRO (inside ATI dir).

The font color is currenty fixed. It would be possible to implement this.
Unfortunately I don't have much time at the moment for cosmetic adjustment.

If someone make a pull request, i will accept it to the branch

**Comment by dezem** [comment]
Closed, added basic support for coloring the text -> https://github.com/dezem/AtmoXL-Titel-Installer/releases/tag/1.7.0

Look at -> https://github.com/dezem/AtmoXL-Titel-Installer#coloring-support

Maybe i add more features in the future...
