### ISSUE TITLE
Bug in nsz decompression

### ISSUE THREAD

**Issue by duckbill007** [dezem/AtmoXL-Titel-Installer#27]
https://github.com/dezem/AtmoXL-Titel-Installer/blob/612b947b5d43985922ded4f1e2e873794147d945/source/nx/nca_writer.cpp#L244

Wrong condition.
Correct: (input.pos < input.size || output.pos > 0)

Last input chunk can produce more that 1 output chunk.

**Comment by dezem** [comment]
Thanks @duckbill007
i fixed that line -> https://github.com/dezem/AtmoXL-Titel-Installer/commit/fe0ead9e4f44361216db52837ed9f7701c7a4921
