### ISSUE TITLE
[Localization updated] Traditional Chinese langs for AtmoXL-Titel-Installer 1.5.1

### ISSUE THREAD

**Issue by qazrfv1234** [dezem/AtmoXL-Titel-Installer#3]
Hi,
the attachment for AtmoXL-Titel-Installer 1.5.1 (base on the latest en.json )

[zh-TW for 1.5.1.zip](https://github.com/dezem/AtmoXL-Titel-Installer/files/6815448/zh-TW.for.1.5.1.zip)

Many thanks,
Leo

**Comment by dezem** [comment]
THX, i will include it with the next release 👍

**Comment by dezem** [comment]
Included in 1.5.2 -> https://github.com/dezem/AtmoXL-Titel-Installer/compare/1.5.1...master#diff-ab124baeb2e82231aae60879776149ae8e2ace7755cd8b51452a4b2b8323a057

Thanks 👍
