### ISSUE TITLE
Support for new storage format

### ISSUE THREAD

**Issue by Dsseed** [dezem/AtmoXL-Titel-Installer#5]
Titles such as Lost in Random, Last Stop, and NMH3 cannot be installed properly due to the new storage format they have.

**Comment by Dsseed** [comment]
Currently the installer that supports the new format is DBI 330 Tinfoil R13

**Comment by dezem** [comment]
Should be fixed with the 1.5.2 release
https://github.com/dezem/AtmoXL-Titel-Installer/compare/1.5.1...master#diff-effbc5bbe41bb1c599557f3a09437343332f56f85e8614a247d1f717a3a3a892

Thanks goes to R-YaTian 👍
