### ISSUE TITLE
Stuck in Firmware 13.0.0

### ISSUE THREAD

**Issue by Borrajo** [dezem/AtmoXL-Titel-Installer#6]
https://github.com/dezem/AtmoXL-Titel-Installer/blob/8ad1cd7c618fd7b1c81650b75da5d7e57951bf06/source/ui/sdInstPage.cpp#L51

The firmware 13.0.0 has denied the access to SD root.
the program throw an axception and it try go to up parent folder, but doesn't has more levels. the program enter in a infinite loop and crash.

From Team Racoon with Love.

**Comment by dezem** [comment]
Denied access to sd card on FW13.0.0?
Have you more infos to that?
This info is new to me, and on my console it works fine with FW13.0.0 and AMS 1.1.1.

Maybe faulty AMS setup?

**Comment by Borrajo** [comment]
Maybe, I don't know. Can you check if you can access via FTP to root folder SD ? I got access denied, but only in the root folder.

**Comment by dezem** [comment]
ftpd 3.1.0 and winscp works fine on sd root, here my screen 
![ftpd_sd_root](https://user-images.githubusercontent.com/11005072/135145816-5ad378a7-1411-4e88-9c61-4c50be7bcbfc.png)

**Comment by Borrajo** [comment]
I have activated the hekate's bootprotect, and that thing denied the access but only in the firmware 13.0.0. 
try, in hekate_ipl.ini 
`[config]  
bootprotect=1`
and try again access to root folder SD from AtmoXL or via FTP.
I'll working on this.

**Comment by dezem** [comment]
Thanks @Borrajo i fixed it in 1.5.3 👍 
https://github.com/dezem/AtmoXL-Titel-Installer/releases/tag/1.5.3
