### ISSUE TITLE
[Localization updated] Traditional Korean langs for AtmoXL-Titel-Installer 1.5.1

### ISSUE THREAD

**Issue by jkh0kr** [dezem/AtmoXL-Titel-Installer#7]
Hi,
the attachment for AtmoXL-Titel-Installer 1.5.1 (base on the latest en.json )

[ko-KR.zip](https://github.com/dezem/AtmoXL-Titel-Installer/files/7252456/ko-KR.zip)

Many thanks,
Leo

**Comment by dezem** [comment]
Hi there,
thanks for your contribution.

I will commit it later...and close it here

**Comment by dezem** [comment]
Korean lang added -> https://github.com/dezem/AtmoXL-Titel-Installer/commit/c6ad3c69186a5642cd363a2824e28fda478efee7
