### ISSUE TITLE
The app will not auto exit after the online update

### ISSUE THREAD

**Issue by carcaschoi** [dezem/AtmoXL-Titel-Installer#8]
I need to press home button to exit the app

**Comment by dezem** [comment]
There is no problem
https://github.com/dezem/AtmoXL-Titel-Installer/blob/fceb9360b770e58b46d00908e9f7b6138233e854/source/ui/optionsPage.cpp#L66-L67

Works fine over album or nsp injection (title override).

Maybe your are using an custom NRO forwarder?
Which breaks the success exit of ATI...

**Comment by carcaschoi** [comment]
I use album

**Comment by carcaschoi** [comment]
Bug video: https://youtu.be/2rlYHSoIqTU

The app can still update to 1.5.4

**Comment by dezem** [comment]
Oh ya its a bug, if auto update is enabled and using applet mode.

Could you try the attached version.
[AtmoXL-Titel-Installer_1.5.3.zip](https://github.com/dezem/AtmoXL-Titel-Installer/files/7272218/AtmoXL-Titel-Installer_1.5.3.zip)

Replace it on your switch and update to the 1.5.4 online from github.
I made a silent update to the ZIP file on github, so you are safe for the next release.

**Comment by carcaschoi** [comment]
Fixed

**Comment by dezem** [comment]
Thanks, fixed with -> https://github.com/dezem/AtmoXL-Titel-Installer/commit/6926c19e01d638fead3a91998b3309bb581d9414
